config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  get 'carts/purchased'

  devise_for :users
  resources :members
  resources :first_names
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'members#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/first_name.rb
class FirstName < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end

  def purchased
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :nickname, :email, :emergency_contact, :emerg_phone, :med_history, :dependant, :vehicle_licence, :agrees_waiver)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/carts/purchased.html.erb
<h1>Carts#purchased</h1>
<p>Find me in app/views/carts/purchased.html.erb</p>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_header.html.erb
<div class="row">
  <nav class="top-bar column" data-topbar>

      <ul class="title-area">
        <li class="name">
          <h1>
            <a href="/">
              <i class="fi-music"></i> Freespace Collective
            </a>
          </h1>
        </li>
        <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
        <ul class="right">
          <%if signed_in?%>
            <li><%=link_to current_user.email, edit_user_registration_path%></li>
            <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
          <%else%>
            <li><%=link_to "Register", new_user_registration_path%></li>
            <li><%=link_to "Login", new_user_session_path%></li>
          <%end%>
        </ul>
      </section>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- This is the Layout file! -->
<html>
  <head>
    <title>Freespace</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script> <!-- icons -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <br/>

  <%= render "layouts/header" %>

  <%= render "layouts/alerts" %>

  <div id="main-content" class="row full-min-height">
    <%= yield %>
  </div>

  <footer class="row">
      <div class="large-12 columns">
      <hr> <p><i class="fas fa-copyright"></i> Freespace Collective<br>
      Built and designed by Erav with <i class="fas fa-heartbeat" style="color:red;"></i> and <i class="fas fa-coffee"></i></p>
    </div>
  </footer>

  <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :member_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :member_last_name %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :member_nickname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :member_email %>
  </div>

  <div class="field">
    <%= form.label :emergency_contact %>
    <%= form.text_field :emergency_contact, id: :member_emergency_contact %>
  </div>

  <div class="field">
    <%= form.label :emerg_phone %>
    <%= form.text_field :emerg_phone, id: :member_emerg_phone %>
  </div>

  <div class="field">
    <%= form.label :med_history %>
    <%= form.text_field :med_history, id: :member_med_history %>
  </div>

  <div class="field">
    <%= form.label :dependant %>
    <%= form.text_field :dependant, id: :member_dependant %>
  </div>

  <div class="field">
    <%= form.label :vehicle_licence %>
    <%= form.text_field :vehicle_licence, id: :member_vehicle_licence %>
  </div>

  <div class="field">
    <%= form.label :agrees_waiver %>
    <%= form.text_field :agrees_waiver, id: :member_agrees_waiver %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="column">Members</h1>


<p>this page should be accesable for crew only!</p>

<div class="table-scroll">
  <table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Nickname</th>
      <th>Email</th>
      <th>Emergency contact</th>
      <th>Emerg phone</th>
      <th>Med history</th>
      <th>Dependant</th>
      <th>Vehicle licence</th>
      <th>Agrees To waiver</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.nickname %></td>
        <td><%= member.email %></td>
        <td><%= member.emergency_contact %></td>
        <td><%= member.emerg_phone %></td>
        <td><%= member.med_history %></td>
        <td><%= member.dependant %></td>
        <td><%= member.vehicle_licence %></td>
        <td><%= member.agrees_waiver %></td>
        <div class="small button-group">
        <td><%= link_to 'Show', member, class:'clear button tiny' %></td>
        <td><%= link_to 'Edit', edit_member_path(member), class:' clear button tiny warning' %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' }, class:'clear button tiny alert' %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

  <i class="fi-torsos-all-female fa-2x"></i>
  <%= link_to 'New Member', new_member_path, class:'button success' %>
  </i>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @member.nickname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Emergency contact:</strong>
  <%= @member.emergency_contact %>
</p>

<p>
  <strong>Emerg phone:</strong>
  <%= @member.emerg_phone %>
</p>

<p>
  <strong>Med history:</strong>
  <%= @member.med_history %>
</p>

<p>
  <strong>Dependant:</strong>
  <%= @member.dependant %>
</p>

<p>
  <strong>Vehicle licence:</strong>
  <%= @member.vehicle_licence %>
</p>

<p>
  <strong>Agrees waiver:</strong>
  <%= @member.agrees_waiver %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>